### ISSUE TITLE
[LinesCounter] Не дотестировали

### ISSUE THREAD

**Issue by pavel-b-novikov** [MarkGuryanov/nsudotnet#1]
> line[i + 1] == '*'

Если у меня просто большая формула, где деление в конце строки переносится на следующую - ваша программа свалится. 
Вот что мешает людям реализовывать эту задачу через флаги состояний - в корне не понимаю.

**Comment by MarkGuryanov** [comment]
Почему же? Там `for (int i = 0; i < line.Length - 1; i++)`
Значит `(i + 1) < line.Length`, и всё корректно.
Даже проверил на соответствующем тесте.

**Comment by pavel-b-novikov** [comment]
Перечитал. Да, истину глаголете.
