### ISSUE TITLE
[Enigma] Внезапно, строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [MarkGuryanov/nsudotnet#4]
Сама задача в порядке, хоть и немного странновато сделана.

ключевых момента по сути 2
1) перестаньте конкатенировать через +. Глаз режет, правда
2) ```args[0].ToLower() == "encrypt"``` как вы думаете, к чему я должен придраться в этой строке?

**Comment by MarkGuryanov** [comment]
Исправил:
1) Вместо + теперь использую string.Concat
2) Вообще args[0] может быть null, и вызов метода сгенерирует исключение. Я решил убрать ToLower()

**Comment by pavel-b-novikov** [comment]
Вообще-то я имел в виду, что .ToLower плодит лишнюю строку и правильнее писать String.Compare
